import "server-only"

import { randomBytes } from "node:crypto"
import { mkdir, readFile, rename, writeFile } from "node:fs/promises"
import { join } from "node:path"

/**
 * The one pi extension this app ships, generated onto disk the same way
 * `models.json` is: a string constant here, written under
 * `$AGENT_UI_DIR/pi/extensions` and loaded with an explicit `--extension`.
 *
 * It exists because pi's four built-in tools have no way to ask a question.
 * Everything else about a turn is the model talking *at* the user; this is the
 * one place it can stop and wait for them, and the answer comes back as the
 * tool's result, so the same run carries on with it.
 *
 * Extensions are loaded through jiti, so the TypeScript needs no build step,
 * and `typebox` resolves from anywhere on disk because pi aliases it for the
 * loader. Nothing else is imported: the fewer names this file reaches for, the
 * fewer ways a pi upgrade can stop it loading.
 */

/**
 * Deliberately not one of the names `isAskToolName` in the vendored
 * `ask-question.tsx` claims (`ask`, `ask_user`, `AskQuestion`, `questions`).
 * Those belong to the *between-turns* ask flow, which answers by rewriting the
 * transcript and sending a fresh user turn — while this tool's run is still
 * open and blocked on stdin. One question must not offer two answer buttons
 * that mean different things, so this one keeps out of that name space and the
 * provider publishes the wait as its own `question` row instead.
 */
export const PI_ASK_TOOL = "request_user_input"

export const PI_EXTENSION_FILE = "ask-user.ts"

const SOURCE = `// Generated by Agent UI — edits are overwritten. See lib/pi-extension.ts.
import { Type } from "typebox"

const Params = Type.Object({
  question: Type.String({ description: "The question to put to the user." }),
  options: Type.Optional(
    Type.Array(Type.String(), {
      description:
        "Answers to choose between. Omit for a free-text answer.",
    })
  ),
})

export default function askUser(pi: any) {
  pi.registerTool({
    name: ${JSON.stringify(PI_ASK_TOOL)},
    label: "Ask the user",
    description:
      "Ask the person you are working for a question and wait for their answer. " +
      "Use it when a choice is theirs to make or when you are missing something " +
      "only they can tell you — not for anything you can find out yourself.",
    promptSnippet: "Ask the user a question and wait for the answer",
    parameters: Params,
    executionMode: "sequential",
    async execute(_id: string, params: any, _signal: any, _onUpdate: any, ctx: any) {
      const question = String(params?.question ?? "").trim()
      if (!question) throw new Error("A question is required.")
      const options: string[] = Array.isArray(params?.options)
        ? params.options
            .map((option: unknown) => String(option ?? "").trim())
            .filter((option: string) => option.length > 0)
        : []
      if (!ctx?.hasUI) {
        return {
          content: [
            {
              type: "text",
              text: "There is nobody to ask right now — decide for yourself and say what you assumed.",
            },
          ],
          details: { question, options, answer: null },
        }
      }
      const answer =
        options.length > 0
          ? await ctx.ui.select(question, options)
          : await ctx.ui.input(question)
      const text = typeof answer === "string" && answer.trim() ? answer.trim() : null
      return {
        content: [
          {
            type: "text",
            text: text
              ? "The user answered: " + text
              : "The user did not answer. Carry on without it and say what you assumed.",
          },
        ],
        details: { question, options, answer: text },
      }
    },
  })
}
`

/**
 * Writes the extension and answers with its path. Replaced rather than
 * rewritten, and only when the bytes changed: a concurrent turn may be loading
 * this exact file, and it must see a whole one.
 */
export async function writePiExtension(configDir: string): Promise<string> {
  const dir = join(configDir, "extensions")
  const path = join(dir, PI_EXTENSION_FILE)
  const current = await readFile(path, "utf8").catch(() => null)
  if (current === SOURCE) return path
  await mkdir(dir, { recursive: true, mode: 0o700 })
  const tmp = `${path}.${process.pid.toString(36)}${randomBytes(3).toString("hex")}.tmp`
  await writeFile(tmp, SOURCE, { encoding: "utf8", mode: 0o600 })
  await rename(tmp, path)
  return path
}
